# Site settings
title: SEO Love Letter
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A love letter to everything that Airbnb and SEO has brought to my life.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://seoloveletter.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  seoloveletter
permalink: :categories/:title
# Build settings
markdown: kramdown
